automation:
    label: automation
    permalink: /automation
    description: Articles about automations in Power Platform

azure:
    label: Azure
    permalink: /azure
    description: Articles about using Azure services

azureFunctions:
    label: Azure Functions
    permalink: /azure-functions
    description: Articles about using Azure Functions

azureLogicApps:
    label: Azure Logic Apps
    permalink: /azure-logic-apps
    description: Articles about using Azure Logic Apps

bicep:
    label: Bicep
    permalink: /bicep
    description: Articles about using Bicep for Azure deployments

c#:
    label: C#
    permalink: /csharp
    description: Using C# in Power Platform

clientSideScripting:
    label: Client Side Scripting
    permalink: /client-side-scripting
    description: Articles about client side scripting in model-driven Power Apps

dataverse:
    label: Dataverse
    permalink: /dataverse
    description: Articles regarding all things Dataverse

design:
    label: Design
    permalink: /design
    description: Articles about design principles

emoji:
    label: Emoji
    permalink: /emoji

hello:
    label: Hello
    permalink: /hello

icon:
    label: Icon
    permalink: /icon

introduction:
    label: Introduction
    permalink: /introduction

javaScript:
    label: JavaScript
    permalink: /javascript

playwright:
    label: Playwright
    permalink: /playwright
    description: Articles about using Playwright for various things

plugin:
    label: Plugin
    permalink: /plugin
    description: Articles about Dataverse Plugins

powerApps:
    label: Power Apps
    permalink: /power-apps
    description: Articles about Power Apps

powerPlatform:
    label: Power Platform
    permalink: /power-platform

python:
    label: Python
    permalink: /python

workflow:
    label: Workflow
    permalink: /workflow
    description: Articles about enhancing your workflows
